development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: scheduling_development
  pool: 5
  username: root
  password: root


production:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/production.sqlite3
