development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: scheduling2_development
  pool: 5
  username: root
  password: root

production:
  adapter: postgresql
  encoding: unicode
  pool: 5